/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.marqueepossystem;

import static com.mycompany.marqueepossystem.TicketsDashboard.clearing;
import static com.mycompany.marqueepossystem.TicketsDashboard.removing;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Theojohn Sosa
 */
public class SnacksSubMenu extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public SnacksSubMenu() {
        initComponents();
        jTable1.setModel(ShareTableModel.ticketsTableModel);
        updateTotalAmountField();
        setLocationRelativeTo(null);
    }
    
    private void updateTotalAmountField() {
        totalAmountTextField.setText("₱" + String.format("%.2f", ShareTableModel.totalAmount));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        signOutButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalAmountTextField = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        placeOrderButton = new javax.swing.JButton();
        creditButton = new javax.swing.JToggleButton();
        mobileButton = new javax.swing.JToggleButton();
        cashButton = new javax.swing.JToggleButton();
        voidButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        soloSnacksButton = new javax.swing.JButton();
        comboMealsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(19, 19, 19));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marquee.");

        signOutButton.setBackground(new java.awt.Color(255, 255, 255));
        signOutButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        signOutButton.setForeground(new java.awt.Color(0, 0, 0));
        signOutButton.setText("SIGN OUT");
        signOutButton.setBorder(null);
        signOutButton.setFocusPainted(false);
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });

        adminButton.setBackground(new java.awt.Color(255, 255, 255));
        adminButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        adminButton.setForeground(new java.awt.Color(0, 0, 0));
        adminButton.setText("ADMIN");
        adminButton.setBorder(null);
        adminButton.setFocusPainted(false);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setText("BACK");
        backButton.setBorder(null);
        backButton.setFocusPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(signOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(99, 99, 99));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Each", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel6.setBackground(new java.awt.Color(217, 217, 217));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Total: ");

        totalAmountTextField.setBackground(new java.awt.Color(217, 217, 217));
        totalAmountTextField.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        totalAmountTextField.setForeground(new java.awt.Color(0, 0, 0));
        totalAmountTextField.setBorder(null);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalAmountTextField))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(totalAmountTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        removeButton.setBackground(new java.awt.Color(255, 255, 255));
        removeButton.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 0, 0));
        removeButton.setText("REMOVE");
        removeButton.setBorder(null);
        removeButton.setFocusPainted(false);
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(255, 255, 255));
        clearButton.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 0, 0));
        clearButton.setText("CLEAR");
        clearButton.setBorder(null);
        clearButton.setFocusPainted(false);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        placeOrderButton.setBackground(new java.awt.Color(0, 0, 0));
        placeOrderButton.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        placeOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        placeOrderButton.setText("PLACE ORDER");
        placeOrderButton.setBorder(null);
        placeOrderButton.setFocusPainted(false);
        placeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderButtonActionPerformed(evt);
            }
        });

        creditButton.setBackground(new java.awt.Color(26, 93, 250));
        creditButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        creditButton.setForeground(new java.awt.Color(255, 255, 255));
        creditButton.setText("CREDIT");
        creditButton.setBorder(null);
        creditButton.setFocusPainted(false);

        mobileButton.setBackground(new java.awt.Color(253, 88, 22));
        mobileButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        mobileButton.setForeground(new java.awt.Color(255, 255, 255));
        mobileButton.setText("MOBILE");
        mobileButton.setBorder(null);
        mobileButton.setFocusPainted(false);

        cashButton.setBackground(new java.awt.Color(242, 182, 3));
        cashButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cashButton.setForeground(new java.awt.Color(255, 255, 255));
        cashButton.setText("CASH");
        cashButton.setBorder(null);
        cashButton.setFocusPainted(false);

        voidButton.setBackground(new java.awt.Color(255, 255, 255));
        voidButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        voidButton.setForeground(new java.awt.Color(0, 0, 0));
        voidButton.setText("VOID");
        voidButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        voidButton.setFocusPainted(false);
        voidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voidButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(placeOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(voidButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(creditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mobileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voidButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(placeOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(234, 234, 234));

        soloSnacksButton.setBackground(new java.awt.Color(0, 0, 0));
        soloSnacksButton.setFont(new java.awt.Font("Calibri", 1, 35)); // NOI18N
        soloSnacksButton.setForeground(new java.awt.Color(255, 255, 255));
        soloSnacksButton.setText("SOLO SNACKS");
        soloSnacksButton.setFocusPainted(false);
        soloSnacksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soloSnacksButtonActionPerformed(evt);
            }
        });

        comboMealsButton.setBackground(new java.awt.Color(0, 0, 0));
        comboMealsButton.setFont(new java.awt.Font("Calibri", 1, 35)); // NOI18N
        comboMealsButton.setForeground(new java.awt.Color(255, 255, 255));
        comboMealsButton.setText("COMBO MEALS");
        comboMealsButton.setFocusPainted(false);
        comboMealsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMealsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soloSnacksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboMealsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(soloSnacksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMealsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure? You will be signed out.", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_signOutButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure? You will be signed out.", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_adminButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        new CashierDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void soloSnacksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soloSnacksButtonActionPerformed
        new SoloSnacksDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_soloSnacksButtonActionPerformed

    private void comboMealsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMealsButtonActionPerformed
        new ComboMealsDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_comboMealsButtonActionPerformed

    private void placeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtonActionPerformed
        if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No order to be placed.");
        } else {
            if (cashButton.isSelected() && mobileButton.isSelected() && creditButton.isSelected() || cashButton.isSelected() && creditButton.isSelected() || mobileButton.isSelected() && creditButton.isSelected() || cashButton.isSelected() && mobileButton.isSelected()) {
                JOptionPane.showMessageDialog(null, "Select ONLY one mode of payment.");
            } else {
                if (cashButton.isSelected()) { 
                    String cashPaymentStr = JOptionPane.showInputDialog("Enter Cash Payment: ");
                    double cashPayment = Double.parseDouble(cashPaymentStr);
                    if (!cashPaymentStr.isEmpty()) {
                        if (cashPayment >= ShareTableModel.totalAmount) {
                            int choice = JOptionPane.showConfirmDialog(null, "Confirm Payment?", "Confirmation", JOptionPane.YES_NO_OPTION);
                            if (choice == JOptionPane.YES_OPTION) {
                                ShareTableModel.change = cashPayment - ShareTableModel.totalAmount;
                                JOptionPane.showMessageDialog(null, "Change: " + String.format("%.2f", ShareTableModel.change));
                                JOptionPane.showMessageDialog(null, "Successful Payment!");
                                ReceiptManager receiptManager = new ReceiptManager();
                                String receiptText = receiptManager.generateReceipt(ShareTableModel.ticketsTableModel, ShareTableModel.totalAmount, "Cash", cashPayment);
                                String htmlReceipt = "<html><body style='width: 400px; font-family: monospace;'>" + receiptText.replaceAll("\n", "<br>") + "</body></html>";
                                JLabel label = new JLabel(htmlReceipt);
                                JScrollPane scrollPane = new JScrollPane(label);
                                scrollPane.setPreferredSize(new Dimension(500, 400));
                                JOptionPane.showMessageDialog(null, receiptText, "Receipt", JOptionPane.INFORMATION_MESSAGE);
                                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                                model.setRowCount(0);
                                ShareTableModel.totalAmount = 0.00;
                                totalAmountTextField.setText("₱0.00");
                                clearing = false;
                                removing = false;
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Insufficient Amount.");
                        }
                    }
                }

                if (mobileButton.isSelected()) {
                    String phoneNumber = JOptionPane.showInputDialog("Enter Phone Number: ");
                    String validNumbers = "0895, 0896, 0897, 0898, 0905, 0906, 0907, 0908, 0909," +
                                          "0910, 0911, 0912, 0913, 0914, 0915, 0916, 0917, 0920," +
                                          "0921, 0926, 0927, 0928, 0929, 0930, 0935, 0936, 0937," +
                                          "0938, 0939, 0945, 0946, 0947, 0948, 0949, 0950, 0952," +
                                          "0953, 0954, 0955, 0956, 0962, 0963, 0965, 0966, 0967," +
                                          "0968, 0969, 0970, 0975, 0976, 0977, 0978, 0979, 0980, 0982," +
                                          "0989, 0994, 0995, 0996, 0997, 0998, 0999,";
                    if (phoneNumber != null && phoneNumber.matches("\\d{11}") && validNumbers.contains(phoneNumber.substring(0, 4) + ",")) {
                        String paymentStr = JOptionPane.showInputDialog("Enter Payment: ");
                        double mobilePayment = Double.parseDouble(paymentStr);
                        if (!paymentStr.isEmpty()) {
                            if (mobilePayment >= ShareTableModel.totalAmount) {
                                int choice = JOptionPane.showConfirmDialog(null, "Confirm Payment?", "Confirmation", JOptionPane.YES_NO_OPTION);
                                if (choice == JOptionPane.YES_OPTION) {
                                    ShareTableModel.change = mobilePayment - ShareTableModel.totalAmount;
                                    JOptionPane.showMessageDialog(null, "Change: " + String.format("%.2f", ShareTableModel.change));
                                    JOptionPane.showMessageDialog(null, "Successful Payment!");                              
                                    ReceiptManager receiptManager = new ReceiptManager();
                                    String receiptText = receiptManager.generateReceipt(ShareTableModel.ticketsTableModel, ShareTableModel.totalAmount, "Mobile", mobilePayment);                               
                                    String htmlReceipt = "<html><body style='width: 400px; font-family: monospace;'>" + receiptText.replaceAll("\n", "<br>") + "</body></html>";
                                    JLabel label = new JLabel(htmlReceipt);
                                    JScrollPane scrollPane = new JScrollPane(label);
                                    scrollPane.setPreferredSize(new Dimension(500, 400));
                                    JOptionPane.showMessageDialog(null, receiptText, "Receipt", JOptionPane.INFORMATION_MESSAGE);
                                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                                    model.setRowCount(0);
                                    ShareTableModel.totalAmount = 0.00;
                                    totalAmountTextField.setText("₱0.00");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Insufficient Amount.");
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid phone number. Try again.");
                    }
                }

                if (creditButton.isSelected()) {
                    String creditCardNumber = JOptionPane.showInputDialog("Enter Card Number: ");
                    if (creditCardNumber != null && creditCardNumber.matches("\\d{16}")) {
                        String paymentStr = JOptionPane.showInputDialog("Enter Payment: ");
                        double creditPayment = Double.parseDouble(paymentStr);
                        if (!paymentStr.isEmpty()) {
                            if (creditPayment >= ShareTableModel.totalAmount) {
                                int choice = JOptionPane.showConfirmDialog(null, "Confirm Payment?", "Confirmation", JOptionPane.YES_NO_OPTION);
                                if (choice == JOptionPane.YES_OPTION) {
                                    ShareTableModel.change = creditPayment - ShareTableModel.totalAmount;
                                    JOptionPane.showMessageDialog(null, "Change: " + String.format("%.2f", ShareTableModel.change));
                                    JOptionPane.showMessageDialog(null, "Successful Payment!");
                                    ReceiptManager receiptManager = new ReceiptManager();
                                    String receiptText = receiptManager.generateReceipt(ShareTableModel.ticketsTableModel, ShareTableModel.totalAmount, "Credit", creditPayment);
                                    String htmlReceipt = "<html><body style='width: 400px; font-family: monospace;'>" + receiptText.replaceAll("\n", "<br>") + "</body></html>";
                                    JLabel label = new JLabel(htmlReceipt);
                                    JScrollPane scrollPane = new JScrollPane(label);
                                    scrollPane.setPreferredSize(new Dimension(500, 400));
                                    JOptionPane.showMessageDialog(null, receiptText, "Receipt", JOptionPane.INFORMATION_MESSAGE);
                                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                                    model.setRowCount(0);
                                    ShareTableModel.totalAmount = 0.00;
                                    totalAmountTextField.setText("₱0.00");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Insufficient Amount.");
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid card number.");
                    }
                }
            }
        }

        cashButton.setSelected(false);
        mobileButton.setSelected(false);
        creditButton.setSelected(false);
    }//GEN-LAST:event_placeOrderButtonActionPerformed

    static boolean removing = false;
    
    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if (removing) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int rowCount = model.getRowCount();
            if (rowCount > 0) {
                String totalValueStr = model.getValueAt(rowCount - 1, 3).toString().replace("₱", "").replace(",", "").trim();            
                double totalValue = Double.parseDouble(totalValueStr);
                ShareTableModel.totalAmount -= totalValue;
                model.removeRow(rowCount - 1);
                totalAmountTextField.setText("₱" + String.format("%.2f", ShareTableModel.totalAmount));
            }
        } else {
            JOptionPane.showMessageDialog(null, "Admim Void Required.");
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    static boolean clearing = false;
    
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        if (clearing) {
            int choice = JOptionPane.showConfirmDialog(null, "Are you sure? Everything will be cleared.", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Order Cleared.");
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                ShareTableModel.totalAmount = 0.00;
                totalAmountTextField.setText("₱0.00");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Admim Void Required.");
        }
    }//GEN-LAST:event_clearButtonActionPerformed

    private void voidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voidButtonActionPerformed
        String voidCode = JOptionPane.showInputDialog("Enter Admin Void Code: ");
        if (voidCode.equals("1234")) {
            int choice = JOptionPane.showConfirmDialog(null, "Confirm Void?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(null, "Void Activated.");
                clearing = true;
                removing = true;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Void Code.");
        }
    }//GEN-LAST:event_voidButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnacksSubMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnacksSubMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnacksSubMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnacksSubMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnacksSubMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton backButton;
    private javax.swing.JToggleButton cashButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton comboMealsButton;
    private javax.swing.JToggleButton creditButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton mobileButton;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton signOutButton;
    private javax.swing.JButton soloSnacksButton;
    private javax.swing.JTextField totalAmountTextField;
    private javax.swing.JButton voidButton;
    // End of variables declaration//GEN-END:variables
}